apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
      - name: init-backend
        image: busybox
        command: ['sh', '-c', 'cp -r /django/khedma/build/static/. /static/']
        volumeMounts:
        - name: static-volume
          mountPath: /static
        - name: temp-static
          mountPath: /django/khedma/build/static
      containers:
      - name: backend
        image: lou4y/backend:90b9dd4
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: media-volume
          mountPath: /django/khedma/media
        - name: static-volume
          mountPath: /django/khedma/build/static
      volumes:
      - name: media-volume
        persistentVolumeClaim:
          claimName: backend-media-pvc
      - name: static-volume
        persistentVolumeClaim:
          claimName: backend-static-pvc
      - name: temp-static
        emptyDir: {}
