apiVersion: v1
kind: PersistentVolume
metadata:
  name: frontend-build-pv
  namespace: dev
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/react-build
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: ""
