apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lou4y/frontend:5f7106fb1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-config
          mountPath: /etc/frontend/conf.d
        - name: media-volume
          mountPath: /django/khedma/media
      volumes:
      - name: frontend-config
        persistentVolumeClaim:
          claimName: frontend-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: backend-media-pvc
