apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: lou4y/frontend:90b9dd4
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d
        - name: media-volume
          mountPath: /django/khedma/media/   # Media files mount
        - name: static-volume
          mountPath: /usr/share/nginx/html/static
      volumes:
      - name: nginx-config-volume
        persistentVolumeClaim:
          claimName: nginx-config-pvc
      - name: media-volume
        persistentVolumeClaim:
          claimName: backend-media-pvc
      - name: static-volume
        persistentVolumeClaim:
          claimName: backend-static-pvc