apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: dev
data:
  nginx.conf: |
    upstream api {
        server backend:8000;  # Define your backend service
    }

    server {
        listen 80;

        # Uncomment if you're using a domain
        #server_name khedma.site www.khedma.site;

        # SSL certificate configuration (uncomment if needed)
        #ssl_certificate /etc/letsencrypt/live/khedma.site/fullchain.pem;
        #ssl_certificate_key /etc/letsencrypt/live/khedma.site/privkey.pem;
        # Other SSL configurations...

        location / {
            index index.html;
            try_files $uri $uri/ /index.html;
            root /usr/share/nginx/html/;  # Adjust the root path if necessary
        }

        location /api/ {
            proxy_pass http://api;  # Using upstream defined earlier
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /usr/share/nginx/html/static/;  # Ensure this path is correct
        }

        location /media/ {
            alias /django/khedma/media/;  # Ensure this path is correct
            autoindex on;  # Optional: Enable directory listing
        }
    }
