apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx
        - name: react-build-volume
          mountPath: /usr/share/nginx/html  # Serve React build files from here
        - name: media-volume
          mountPath: /var/www/react   # Media files mount
      volumes:
      - name: nginx-config-volume
        persistentVolumeClaim:
          claimName: nginx-config-pvc
      - name: react-build-volume
        persistentVolumeClaim:
          claimName: frontend-pvc  # Uses the PVC from the frontend pod
      - name: media-volume
        persistentVolumeClaim:
          claimName: backend-media-pvc
