apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-postgres-pv
  namespace: production
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /mnt/data/production_postgres
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-postgres-pvc
  namespace: production
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
