apiVersion: v1
kind: PersistentVolume
metadata:
  name: production-backend-media-pv
  namespace: production
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/production-backend-media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: production-backend-media-pvc
  namespace: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ""
