apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: front-app
spec:
  tls:
  - hosts:
    - temp1234567.ddns.net
    secretName: example-app-tls
  rules:
  - host: temp1234567.ddns.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service: 
            name: my-service
            port: 
              number: 80