apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  namespace: default
data:
  DEBUG: "True"
  REDIS_HOST: "khedma-redis"
  DB_HOST: "postgres-service"
  ALLOWED_HOSTS: "khedma123456789.ddns.net,we-tekup,example-service"
  REACT_ADDRESS: "http://example-service"
  CORS_ALLOWED_ORIGINS: "http://example-service,http://we-tekup,http://khedma123456789.ddns.net,https://khedma123456789.ddns.net"
  SIMPLE_JWT_AUTH_HEADER_TYPES: "JWT"
  JWT_ACCESS_TOKEN_LIFETIME: "60"  # Access token lifetime in minutes
  JWT_REFRESH_TOKEN_LIFETIME: "1440"  # Refresh token lifetime in minutes#
