# Secret
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
type: Opaque
data:
  database: cG9zdGdyZXM=  # Base64 encoded value of "postgresql"
  username: cG9zdGdyZXM=     # Base64 encoded value of "postgres"
  password: cG9zdGdyZXM=     # Base64 encoded value of "postgres"

---
# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgresdb
          image: postgres:15.3-alpine
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: database
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdb
            - name: postgres-secrets
              mountPath: "/etc/postgres-secrets"
              readOnly: true
      volumes:
        - name: postgresdb
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: postgres-secrets
          secret:
            secretName: postgres-secrets

---
# Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
