---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: example-deploy
  labels:
    app: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      imagePullSecrets:
      - name: digitalocean-registry # Ensure this secret exists in the namespace
      containers:
      - name: example-app
        image: digitalocean-registry/frontend:v1.384
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: reactjs-config # Reference the correct ConfigMap name
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: example-service
  labels:
    app: example-app
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
