apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
  labels:
    type: reactnode
spec:
  replicas: 7
  selector:
    matchLabels:
      type: reactnode
  template:
    metadata:
      labels:
        type: reactnode
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: front-app
        image: mohamedamineblibech/frontend:v1.1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "200Mi"
          limits:
            memory: "500Mi"
