apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    type: rs
spec:
  replicas: 7
  template:
    metadata:
      name: my-pod
      labels:
        type: reactnode
    spec:
      containers:
      - name: front-app
        image: mohamedamineblibech/frontend:v1.1
        ports:
          - name: front-app
            containerPort: 3000
            targetPort: 80
#gere les objet nouvellement cree 
  selector:
    matchLabels:
      type: reactnode 
      
