---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: example-deploy
  labels:
    app: example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: example-app
    spec:
      imagePullSecrets:
      - name: dockerhub-secret # Ensure this secret exists in the namespace
      containers:
      - name: example-app
        image: mohamedamineblibech/frontend:v1.25
        ports:
        - containerPort: 3000
        volumeMounts:
          - name: static-volume-mount
            mountPath: /reactjs/khedma/public/static  # Path where React stores its static files
        envFrom:
        - configMapRef:
            name: reactjs-config # Reference the correct ConfigMap name
      volumes:
        - name: static-volume-mount
          persistentVolumeClaim:
            claimName: static-pvc-local


---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: example-service
  labels:
    app: example-app
spec:
  type: LoadBalancer
  selector:
    app: example-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 3000
