apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
  labels:
    type: reactnode
spec:
  replicas: 7
  selector:
    matchLabels:
      type: reactnode
  template:
    metadata:
      namespace: default
      labels:
        type: reactnode
    spec:
      containers:
      - name: front-app
        image: mohamedamineblibech/frontend:v1.1
        ports:
        - containerPort: 3000
