apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: khedma
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: backend
        image: mohamedamineblibech/backend:v12
        ports:
        - containerPort: 8080
