# apiVersion: v1
# kind: Secret
# metadata:
#   namespace: default
#   name: digitalocean-registry
# type: kubernetes.io/dockerconfigjson
# data:
#   .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJyZWdpc3RyeS5kaWdpdGFsb2NlYW4uY29tIjogewogICAgICAiYXV0aCI6ICJaRzl3WDNZeFh6UmtZV1kxTldReU56QTFOV1EwT0ROaU5USXdNVEF3TVRKaU5XTmpaR1kyTlRVMVlqRTFOakZtWWpOak9UVTVZamN3IFptUmhPVFV3T1RFeVltVXlZemM9IgogICAgfQogIH0KfQo=
apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CiAgICAgICJhdXRoIjogImJXOW9ZVzFsWkdGdGFXNWxZbXhwWW1WamFEcGtZMnR5WDNCaGRGOW9TemRaY1c1aE1UbExkM0ZFWWpKbFVsZFhiazh0UzA1b2RVVT0iLAogICAgICAiZW1haWwiOiAiYmxpYmVjaG1lZGFtaW5lQGdtYWlsLmNvbSIKICAgIH0KICB9Cn0K