apiVersion: v1
kind: Secret
metadata:
  namespace: default
  name: dockerhub-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogewogICAgICAgICJ1c2VybmFtZSI6ICJtb2hhbWVkYW1pbmVibGliZWNoIiwKICAgICAgICAicGFzc3dvcmQiOiAiZGNrcl9wYXRfSVYtTEFLLUR2VkpiNmZINEp6ck4tNEFna01VIiwKICAgICAgICAiZW1haWwiOiAiYmxpYmVjaG1lZGFtaW5lQGdtYWlsLmNvbSIKICAgICAgfQogICAgfQogIH0KICA=
