apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: khedma
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  rules:
  - host: khedma123456.ddns.net  # Your domain name
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend-service  # Your service name
            port:
              number: 443  # Your service port
  tls:
  - hosts:
    - khedma123456.ddns.net
    secretName: backend-cert
