apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: default
  name: postgres-pv-local
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgres-pv
