apiVersion: v1
kind: Secret
metadata:
  name: kh-secret
  namespace: default
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLXk9KS1eZjEqbSEyXiQ3PSlhPSQlOSkyY3YlNGEycG9yJW0jQHAzdiFfJXNhISEqYjU=  
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  # JWT_SECRET_KEY: ZGphbmdvX3Rva2VuCg==  # You should consider generating a secure key
##