apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: khedma
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80        # The service port within the cluster
      targetPort: 8080 # The backend container port
      nodePort: 30007  # The external port to access the service
  type: NodePort
