apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: khedma
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80         # The port that the service exposes internally
      targetPort: 8080 # The port that your backend container is listening on
      nodePort: 30001   # The port on the node that will be exposed
  type: NodePort
