apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
    # Port of the container inside the pod
    - targetPort: 3000
      # Port of the service that will expose the container's port
      port: 80
  # Labels to match the target pods
  selector:
    type: reactnode
