apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: static-pvc-local
  namespace: default
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: static-pv-local
