apiVersion: v1
kind: PersistentVolume
metadata:
  name: prod-nginx-config-pv
  namespace: prod
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/prod-nginx-config
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-nginx-config-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""