apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: prod
data:
  nginx.conf: |
    upstream api {
        server backend:8000;
    }

    server {
        listen 80;
        #server_name khedma.site www.khedma.site;

        # SSL certificate configuration
        #ssl_certificate /etc/letsencrypt/live/khedma.site/fullchain.pem;
        #ssl_certificate_key /etc/letsencrypt/live/khedma.site/privkey.pem;
        # Other SSL configurations..

        location / {
            index index.html;
            try_files $uri $uri/ /index.html;
            root /usr/share/nginx/html/;
        }

        location /api/ {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /static/ {
            alias /usr/share/nginx/html/static/;
        }

        location /media/ {
            alias /django/khedma/media/;
            autoindex on;
        }
    }
