apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: prod
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30012  # Choose an appropriate port in the range 30000-32767
