apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: prod
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30011  # Choose an appropriate port in the range 30000-32767
